# Generated by Django 5.1.4 on 2025-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(unique=True)),
                ('is_prime', models.BooleanField()),
                ('is_perfect', models.BooleanField()),
                ('is_armstrong', models.BooleanField()),
                ('properties', models.JSONField()),
                ('digit_sum', models.PositiveIntegerField()),
                ('fun_fact', models.TextField()),
            ],
            options={
                'verbose_name': 'Number Classification',
                'verbose_name_plural': 'Number Classifications',
                'ordering': ['number'],
            },
        ),
    ]
